import Head from 'next/head'
import styles from '../styles/Home.module.css'
import blog from '../blog'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Ehsan marketing is here</h1>

     


    

   
    </div>
  )
}
